[phases.setup]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate && pip install -r requirements.txt",
]

[build]
nixPkgs = ["python311"]  # Явно указываем версию Python

[start]
cmd = "python telegram_ai_bot.py"
